/**
 * Template: Git Workflow Skill + MCP Configuration
 *
 * Generates:
 * - .stackmoss/skill-kit/shared/git-init.skill.md — Git initialization skill template
 * - .stackmoss/mcp-configs/claude.mcp.json — Claude Code project MCP config
 * - .stackmoss/mcp-configs/codex.config.toml — Codex project MCP config
 * - .stackmoss/mcp-configs/antigravity.mcp_config.json — Antigravity MCP config
 *
 * Pure function, deterministic, no LLM.
 *
 * Package registry (verified against npm + real project configs):
 * - Context7:   @upstash/context7-mcp (env: DEFAULT_MINIMUM_TOKENS)
 * - SeqThink:   @modelcontextprotocol/server-sequential-thinking
 * - Postgres:   @modelcontextprotocol/server-postgres (args pattern + timeoutMs)
 * - Notion:     @notionhq/notion-mcp-server (env: NOTION_TOKEN)
 * - Prisma:     npx -y prisma mcp (built-in CLI >= 6.6.0)
 * - GitHub:     docker ghcr.io/github/github-mcp-server (Go, no npx)
 */

import type { GeneratedFile, TemplateInput } from './types.js';

// ─── Git Skill Template ──────────────────────────────────────────

export function renderGitInitSkill(): string {
    return `# Git Initialization Skill

_Adapted from Superpowers git-conventions. This is a shared template — skill-creator adapts it per BRD._

## When to Use
- Immediately after BRD is locked (NORTH_STAR.md status = locked)
- Before any feature implementation begins
- Tech Lead is responsible for guiding this step

## Workflow

### Step 1: Initialize Repository
\\\`\\\`\\\`bash
git init
git add -A
git commit -m "chore: bootstrap project with StackMoss agent team"
\\\`\\\`\\\`

### Step 2: Create GitHub Repository
Tech Lead must guide the user through creating a GitHub repository:

1. Go to https://github.com/new
2. Create repository (match project name from NORTH_STAR.md)
3. Choose visibility (public or private based on BRD constraints)
4. Do NOT initialize with README (repo already has content)

### Step 3: Connect Remote
\\\`\\\`\\\`bash
git remote add origin https://github.com/<owner>/<repo>.git
git branch -M main
git push -u origin main
\\\`\\\`\\\`

### Step 4: Configure Branch Protection (recommended)
- Require pull request before merging to main
- Require at least 1 review approval
- Require status checks to pass (CI)

### Step 5: Set Up .gitignore
Verify .gitignore exists and includes at minimum:
\\\`\\\`\\\`
node_modules/
.env
.env.local
.env.*.local
dist/
build/
*.log
.DS_Store
\\\`\\\`\\\`

## Commit Convention
Use conventional commits with scope:
- \\\`feat(scope): description\\\` — new feature
- \\\`fix(scope): description\\\` — bug fix
- \\\`chore(scope): description\\\` — maintenance
- \\\`docs(scope): description\\\` — documentation
- \\\`refactor(scope): description\\\` — code refactor
- \\\`test(scope): description\\\` — test changes

## Secret Check Before Push
Before any push, review the diff for:
- [ ] No API keys, tokens, or passwords
- [ ] No .env files with real credentials
- [ ] No private keys or certificates
- [ ] No database connection strings with credentials

## Runtime-Specific Skill Paths
| Runtime | Skill Location | Type |
|:--|:--|:--|
| Antigravity | .agent/workflows/git-workflow.md | Workflow (auto-generated) |
| Claude Code | .claude/skills/git-init/SKILL.md | Skill (generated by skill-creator) |
| Codex | .agents/skills/git-init/SKILL.md | Skill (generated by skill-creator) |

## Iron Law
Never push credentials, API keys, or secrets to any remote repository.
`;
}

// ─── MCP Configuration Templates ─────────────────────────────────

/**
 * MCP servers included in all configurations.
 * Verified against: npm registry + real project configs (golfy/.claude/settings.json, golfy/.roo/mcp.json).
 *
 * Postgres: connection string as args[2], with timeoutMs.
 * Context7: @upstash/context7-mcp with DEFAULT_MINIMUM_TOKENS env.
 * Sequential Thinking: key = "sequentialthinking" (no hyphen) — matches Claude permission format.
 * Notion: @notionhq/notion-mcp-server with NOTION_TOKEN env.
 * Prisma: built-in CLI via "npx -y prisma mcp".
 * GitHub: Docker-based Go binary — ghcr.io/github/github-mcp-server.
 */

export function renderClaudeMcpConfig(projectName: string): string {
    return `{
  "_comment": "Project MCP config for ${projectName} — Claude Code",
  "_instructions": "Place this file as .mcp.json in your project root, or merge into .claude/settings.json under mcpServers. Credentials marked [REQUIRED] must be filled by the user before use.",
  "mcpServers": {
    "context7": {
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"],
      "env": {
        "DEFAULT_MINIMUM_TOKENS": "10000"
      }
    },
    "sequentialthinking": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    },
    "postgres": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-postgres", "[REQUIRED] postgresql://user:password@localhost:5432/dbname"],
      "timeoutMs": 60000
    },
    "github": {
      "command": "docker",
      "args": ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "[REQUIRED] Create at https://github.com/settings/tokens — needs repo, read:org scopes"
      }
    },
    "notion": {
      "command": "npx",
      "args": ["-y", "@notionhq/notion-mcp-server"],
      "env": {
        "NOTION_TOKEN": "[REQUIRED] Create internal integration at https://www.notion.so/profile/integrations then share pages with it"
      }
    },
    "prisma": {
      "command": "npx",
      "args": ["-y", "prisma", "mcp"],
      "_note": "Prisma local MCP — requires prisma >= 6.6.0. Only if project uses Prisma ORM."
    }
  }
}
`;
}

export function renderCodexMcpConfig(projectName: string): string {
    return `# Project MCP config for ${projectName} — OpenAI Codex
# Place this file as .codex/config.toml in your project root.
# Credentials marked [REQUIRED] must be filled by the user before use.
# Run \\\`codex mcp add <name> -- <command>\\\` to add servers via CLI instead.

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.context7.env]
DEFAULT_MINIMUM_TOKENS = "10000"

[mcp_servers.sequentialthinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

# Postgres — connection string passed as CLI arg
[mcp_servers.postgres]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-postgres", "[REQUIRED] postgresql://user:password@localhost:5432/dbname"]

# GitHub MCP — Go binary via Docker (no npx available)
[mcp_servers.github]
command = "docker"
args = ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "[REQUIRED] Create at https://github.com/settings/tokens — needs repo, read:org scopes"

[mcp_servers.notion]
command = "npx"
args = ["-y", "@notionhq/notion-mcp-server"]

[mcp_servers.notion.env]
NOTION_TOKEN = "[REQUIRED] Create internal integration at https://www.notion.so/profile/integrations then share pages with it"

# Prisma local MCP — requires prisma >= 6.6.0. Only if project uses Prisma ORM.
[mcp_servers.prisma]
command = "npx"
args = ["-y", "prisma", "mcp"]
`;
}

export function renderAntigravityMcpConfig(projectName: string): string {
    return `{
  "_comment": "Project MCP config for ${projectName} — Antigravity (Google DeepMind)",
  "_instructions": "Open Agent pane > MCP Servers > Manage > View raw config, then merge this content. Credentials marked [REQUIRED] must be filled by the user before use.",
  "mcpServers": {
    "context7": {
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"],
      "env": {
        "DEFAULT_MINIMUM_TOKENS": "10000"
      }
    },
    "sequentialthinking": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    },
    "postgres": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-postgres", "[REQUIRED] postgresql://user:password@localhost:5432/dbname"],
      "timeoutMs": 60000
    },
    "github": {
      "command": "docker",
      "args": ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "[REQUIRED] Create at https://github.com/settings/tokens — needs repo, read:org scopes"
      }
    },
    "notion": {
      "command": "npx",
      "args": ["-y", "@notionhq/notion-mcp-server"],
      "env": {
        "NOTION_TOKEN": "[REQUIRED] Create internal integration at https://www.notion.so/profile/integrations then share pages with it"
      }
    },
    "prisma": {
      "command": "npx",
      "args": ["-y", "prisma", "mcp"],
      "_note": "Prisma local MCP — requires prisma >= 6.6.0. Only if project uses Prisma ORM."
    }
  }
}
`;
}

// ─── Public API ──────────────────────────────────────────────────

export function generateGitAndMcp(input: TemplateInput): GeneratedFile[] {
    const { projectName } = input;
    return [
        { path: '.stackmoss/skill-kit/shared/git-init.skill.md', content: renderGitInitSkill() },
        { path: '.stackmoss/mcp-configs/claude.mcp.json', content: renderClaudeMcpConfig(projectName) },
        { path: '.stackmoss/mcp-configs/codex.config.toml', content: renderCodexMcpConfig(projectName) },
        { path: '.stackmoss/mcp-configs/antigravity.mcp_config.json', content: renderAntigravityMcpConfig(projectName) },
    ];
}
