/**
 * Template: REPO_MAP.md
 * Renders a RepoMapResult into a structured markdown document.
 *
 * Authority: BRD §9, template-engine skill
 */

import type { RepoMapResult } from '../scanner/repo-map.js';
import type { GeneratedFile } from './types.js';

// ─── Generator ──────────────────────────────────────────────────

export function generateRepoMap(result: RepoMapResult, projectName: string): GeneratedFile {
    const lines: string[] = [];

    lines.push(`# Repository Map — ${projectName}`);
    lines.push('');
    lines.push('> Auto-generated by `stackmoss map`. Agents: update this file when you make **structural changes**');
    lines.push('> (new directory, new module, new entry point, moved/deleted module). Do NOT scan the codebase —');
    lines.push('> just add or modify the lines that reflect your change.');
    lines.push('');

    // ── Architecture Overview ────────────────────────────────
    lines.push('## Architecture Overview');
    lines.push('');
    lines.push(`- **Type**: ${formatArchType(result.archType)}`);

    if (result.languages.length > 0) {
        const topLangs = result.languages.slice(0, 3)
            .map(l => `${l.name} (${l.percentage}%)`)
            .join(', ');
        lines.push(`- **Primary languages**: ${topLangs}`);
    }

    if (result.entryPoints.length > 0) {
        const eps = result.entryPoints.slice(0, 5).map(e => `\`${e}\``).join(', ');
        lines.push(`- **Entry points**: ${eps}`);
    }

    if (result.patterns.length > 0) {
        lines.push(`- **Detected patterns**: ${result.patterns.join(', ')}`);
    }

    lines.push('');

    // ── Directory Structure ──────────────────────────────────
    lines.push('## Directory Structure');
    lines.push('');
    lines.push('```text');
    renderDirTree(result.dirAnnotations, lines);
    lines.push('```');
    lines.push('');

    // ── Key Config Files ─────────────────────────────────────
    if (result.configFiles.length > 0) {
        lines.push('## Key Config Files');
        lines.push('');
        lines.push('| File | Purpose |');
        lines.push('|:---|:---|');
        for (const cf of result.configFiles) {
            lines.push(`| \`${cf.path}\` | ${cf.purpose} |`);
        }
        lines.push('');
    }

    // ── Module Dependencies ──────────────────────────────────
    if (result.moduleDeps.length > 0) {
        lines.push('## Module Dependencies');
        lines.push('');
        for (const dep of result.moduleDeps) {
            lines.push(`- \`${dep.from}/\` → \`${dep.to}/\``);
        }
        lines.push('');
    }

    // ── Language Breakdown ───────────────────────────────────
    if (result.languages.length > 0) {
        lines.push('## Language Breakdown');
        lines.push('');
        lines.push('| Language | Files | Share |');
        lines.push('|:---|:---|:---|');
        for (const lang of result.languages.slice(0, 8)) {
            lines.push(`| ${lang.name} | ${lang.fileCount} | ${lang.percentage}% |`);
        }
        lines.push('');
    }

    return {
        path: 'REPO_MAP.md',
        content: lines.join('\n') + '\n',
    };
}

// ─── Helpers ────────────────────────────────────────────────────

function formatArchType(type: string): string {
    switch (type) {
        case 'monorepo': return 'Monorepo';
        case 'workspace': return 'Workspace (multi-package)';
        case 'single': return 'Single project';
        default: return type;
    }
}

function renderDirTree(dirs: DirAnnotationLike[], lines: string[]): void {
    // Group by depth and render as tree
    const sorted = [...dirs]
        .filter(d => d.depth <= 2)
        .sort((a, b) => a.path.localeCompare(b.path));

    for (const dir of sorted) {
        const indent = '    '.repeat(dir.depth);
        const name = dir.path.split('/').pop() ?? dir.path;
        const annotation = dir.purpose ? `  # ${dir.purpose}` : '';
        const count = dir.fileCount > 0 ? ` (${dir.fileCount} files)` : '';
        lines.push(`${indent}├── ${name}/${count}${annotation}`);
    }
}

interface DirAnnotationLike {
    path: string;
    purpose: string;
    fileCount: number;
    depth: number;
}
